---
title: "COVID19 DATA ANALYSIS"
output: 
  html_document: 
    theme: sandstone
theme: sandstone
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r intro, echo=FALSE, warning=FALSE}
setwd("C:\\Users\\Leonardo\\Documents\\POLIMI\\Bayesian-Project\\data-study-of-sampling-strategy")

source(".\\data\\read_data.R") # Data relate to EXCHANGE RATE

```

## Our project result under covid data

The iteration was set to 1500 with 500 burn-in

### First simulation:

```{r, data_1_load, echo=FALSE}
load(".\\covid-data\\covid_1.RData")
result_1 = result
change_point = cumsum(result_1$final_partition)
frequenze = result_1$frequenze
```

The first trial was with:
```{r, data_1, echo=TRUE}
print("m_0 :")
print(result_1$m_0)
```

```{r plot_1, echo=FALSE, fig.width = 12, fig.height= 4}
# Plot the data
plot(log_nord,type = "l", lwd = 2, col = "#FF3300", xlab="Time", ylab="covid case",
     ylim = c(min(dati_finali_log),max(dati_finali_log)))
grid()
lines(log_centro, lwd = 2, col = "#009999")
for (i in 1:length(change_point)){
  abline(v=change_point[i], lty=2)
}
```

```{r plot_1_2, echo=FALSE, fig.width = 12, fig.height= 4}
tot = sum(frequenze)
prob = frequenze/tot
plot(prob, type="h")
```

### Second simulation:

```{r, data_2_load, echo=FALSE}
load(".\\covid-data\\covid_2.RData")
result_2 = result
change_point = cumsum(result_2$final_partition)
frequenze = result_2$frequenze
```

The first trial was with:
```{r, data_2, echo=TRUE}
print("m_0 :")
print(result_2$m_0)
```

```{r plot_2, echo=FALSE, fig.width = 12, fig.height= 4}
# Plot the data
plot(log_nord,type = "l", lwd = 2, col = "#FF3300", xlab="Time", ylab="log-ratio",
     ylim = c(min(dati_finali_log),max(dati_finali_log)))
grid()
lines(log_centro, lwd = 2, col = "#009999")
for (i in 1:length(change_point)){
  abline(v=change_point[i], lty=2, lwd = 3)
}
```

```{r plot_2_2, echo=FALSE, fig.width = 12, fig.height= 4}
plot(frequenze, type="h")
tot = sum(frequenze)
prob = frequenze/tot
plot(prob, type="h")
```